JSDoc 
    = '{' { JSMeta ',' } { defs ',' } JSch '}'
    | 'true'
    | 'false';

JSMeta          = meta-id | meta-schema-uri;
meta-id         = '"$id:"' uri-reference;
meta-schema-uri = '"$schema:"' uri;

JSchObj = '{' JSch '}';
JSchArr = '[{' JSch '}' {',{' JSch '}' } ']';

defs = '"definitions:"{' 
    '"' kword '":' JSchObj
    {',"' kword '":' JSchObj}
'}';

JSch 
    = strSch 
    | numSch
    | intSch
    | objSch
    | arrSch
    | not
    | allOf
    | anyOf
    | enum
    | refSch;

refSch  = '"$ref":' JPointer;
not     = '"not":' JSchObj;
allOf   = '"allOf":' JSchArr;
anyOf   = '"anyOf":' JSchArr;
enum    = '"enum":' '[' Jval {',' Jval} ']';